version: 0.0
os: linux
files:
  - source: /tnp.war
    destination: /opt/tnp/boot/
permissions:
  - object: /opt/tnp/boot/
    pattern: "tnp.war"
    owner: ubuntu
    mode: 666
    type:
      - file
hooks:
  BeforeInstall:
    - location: /scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: /scripts/afterInstall.sh
      timeout: 300
      runas: ubuntu
