spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tnpDB
    username: riphco
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_schema: tnpDB
        format_sql: true
        enable_lazy_load_no_trans: true
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: false
  redis:
    key:
      prefix: ${SPRING_PROFILES_ACTIVE:default}:tnp
    connect-timeout: 10000
    cluster:
      enabled: ${REDIS_CLUSTER_ENABLED:false}
      nodes: ${REDIS_NODES:localhost:6379}
      max-redirects: 3
  data:
    mongodb:
      database: tnpDB
      uri: mongodb://localhost:27017/?connectTimeoutMS=300000&minPoolSize=8&maxPoolSize=32&maxIdleTimeMS=900000
