spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tnpDB
    username: riphco
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 16
      maximum-pool-size: 64
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 60000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_schema: tnpDB
        format_sql: true
        enable_lazy_load_no_trans: true
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: false
  redis:
    key:
      prefix: ${SPRING_PROFILES_ACTIVE:default}:tnp
    connect-timeout: 10000
    cluster:
      enabled: ${REDIS_CLUSTER_ENABLED:false}
      nodes: ${REDIS_NODES:localhost:6379}
      max-redirects: 3
  data:
    mongodb:
      uri: mongodb://localhost:27017/tnpDB?retryWrites=true&maxPoolSize=32&minPoolSize=0&maxIdleTimeMS=300000&waitQueueTimeoutMS=10000&connectTimeoutMS=10000&socketTimeoutMS=60000
